# Generated by Django 6.0.1 on 2026-04-14 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_media_options_discussion_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, default='', max_length=120)),
                ('media_type', models.CharField(blank=True, default='', max_length=20)),
                ('genre', models.CharField(blank=True, default='', max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='personallist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-featured', '-created']},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-featured', '-is_hot', '-updates', '-created']},
        ),
        migrations.AlterModelOptions(
            name='personallist',
            options={'ordering': ['-updates', '-created']},
        ),
        migrations.AddField(
            model_name='discussion',
            name='author_name',
            field=models.CharField(default='mod', max_length=60),
        ),
        migrations.AddField(
            model_name='discussion',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='community',
            field=models.CharField(default='r/unitainment', max_length=80),
        ),
        migrations.AddField(
            model_name='discussion',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussion',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='discussion',
            name='topic_type',
            field=models.CharField(choices=[('general', 'General'), ('anime', 'Anime'), ('game', 'Game'), ('book', 'Book'), ('webseries', 'Web Series'), ('movie', 'Movie')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='media',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='media',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='media',
            name='is_hot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='media',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='season_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='media',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=220),
        ),
        migrations.AddField(
            model_name='personallist',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('anime', 'Anime'), ('game', 'Game'), ('book', 'Book'), ('webseries', 'Web Series'), ('movie', 'Movie')], default='anime', max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(blank=True, default='Hot right now', max_length=40),
        ),
        migrations.AlterField(
            model_name='personallist',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_entries', to='mainapp.media'),
        ),
        migrations.AlterField(
            model_name='personallist',
            name='status',
            field=models.CharField(choices=[('planning', 'Plan To'), ('current', 'Current'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='planning', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='personallist',
            constraint=models.UniqueConstraint(fields=('user', 'media'), name='unique_media_per_user'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
