from django.db import migrations


MEDIA_SEED = [
    {
        "title": "Frieren: Beyond Journey's End",
        "media_type": "anime",
        "genre": "Fantasy",
        "tagline": "Quiet, reflective fantasy with huge emotional weight.",
        "description": "An immortal mage learns what companionship means long after the hero's journey should have ended.",
        "rating": 9.4,
        "release_year": 2023,
        "season_label": "Fantasy comfort pick",
        "status": "Binge-worthy",
        "is_hot": True,
        "featured": True,
        "image_url": "https://placehold.co/1200x720/1d4ed8/f8fafc?text=Frieren",
    },
    {
        "title": "Dandadan",
        "media_type": "anime",
        "genre": "Supernatural",
        "tagline": "Pure chaos, speed, and weird charm.",
        "description": "Teenagers, aliens, and ghosts collide in a series that moves like it had three energy drinks for breakfast.",
        "rating": 8.9,
        "release_year": 2024,
        "season_label": "Hyperactive action slot",
        "status": "Fresh drop",
        "is_hot": True,
        "featured": False,
        "image_url": "https://placehold.co/1200x720/312e81/f8fafc?text=Dandadan",
    },
    {
        "title": "Blue Lock",
        "media_type": "anime",
        "genre": "Sports",
        "tagline": "Soccer turned into a pressure cooker.",
        "description": "An ego-first training program pushes strikers to break, evolve, and chase the one finishing touch that matters.",
        "rating": 8.4,
        "release_year": 2022,
        "season_label": "Competitive energy",
        "status": "Still buzzing",
        "is_hot": True,
        "featured": False,
        "image_url": "https://placehold.co/1200x720/0f766e/f8fafc?text=Blue+Lock",
    },
    {
        "title": "Delicious in Dungeon",
        "media_type": "anime",
        "genre": "Adventure",
        "tagline": "Dungeon crawling with a side of monster cooking.",
        "description": "A fantasy party survives by turning the dungeon itself into dinner without losing the sense of wonder.",
        "rating": 8.8,
        "release_year": 2024,
        "season_label": "Adventure comfort pick",
        "status": "Cozy hit",
        "is_hot": True,
        "featured": False,
        "image_url": "https://placehold.co/1200x720/166534/f8fafc?text=Delicious+in+Dungeon",
    },
    {
        "title": "Hades II",
        "media_type": "game",
        "genre": "Roguelike",
        "tagline": "Stylish runs, sharp writing, and impossible just-one-more energy.",
        "description": "Supergiant's underworld follow-up makes every failed run feel like forward momentum instead of a setback.",
        "rating": 9.2,
        "release_year": 2024,
        "season_label": "Late-night obsession",
        "status": "Hot streak",
        "is_hot": True,
        "featured": True,
        "image_url": "https://placehold.co/1200x720/7c2d12/f8fafc?text=Hades+II",
    },
    {
        "title": "Balatro",
        "media_type": "game",
        "genre": "Deckbuilder",
        "tagline": "Poker logic rewritten as pure brainrot fun.",
        "description": "A tiny deckbuilder with a giant grip on your sleep schedule once the synergies start clicking.",
        "rating": 9.1,
        "release_year": 2024,
        "season_label": "One more run",
        "status": "Community favorite",
        "is_hot": True,
        "featured": False,
        "image_url": "https://placehold.co/1200x720/6d28d9/f8fafc?text=Balatro",
    },
    {
        "title": "Persona 3 Reload",
        "media_type": "game",
        "genre": "RPG",
        "tagline": "Moody social sim meets stylish dungeon runs.",
        "description": "A remake that keeps the melancholy heart of the original while making each day feel sharper and smoother.",
        "rating": 8.9,
        "release_year": 2024,
        "season_label": "Story-heavy pick",
        "status": "Worth the hours",
        "is_hot": True,
        "featured": False,
        "image_url": "https://placehold.co/1200x720/1e3a8a/f8fafc?text=Persona+3+Reload",
    },
    {
        "title": "Animal Well",
        "media_type": "game",
        "genre": "Metroidvania",
        "tagline": "A puzzle box that keeps revealing more layers.",
        "description": "Minimal words, maximal curiosity, and a world built to reward patient weird little experiments.",
        "rating": 8.7,
        "release_year": 2024,
        "season_label": "Indie rabbit hole",
        "status": "Quiet gem",
        "is_hot": True,
        "featured": False,
        "image_url": "https://placehold.co/1200x720/0f172a/f8fafc?text=Animal+Well",
    },
    {
        "title": "Babel",
        "media_type": "book",
        "genre": "Historical Fantasy",
        "tagline": "Translation, empire, and power under a microscope.",
        "description": "Language becomes both scholarship and rebellion in a dark academia story with a lot more teeth than it first appears.",
        "rating": 9.0,
        "release_year": 2022,
        "season_label": "Smart-page-turner",
        "status": "Book club magnet",
        "is_hot": True,
        "featured": True,
        "image_url": "https://placehold.co/1200x720/92400e/f8fafc?text=Babel",
    },
    {
        "title": "Project Hail Mary",
        "media_type": "book",
        "genre": "Science Fiction",
        "tagline": "Big science, bigger heart.",
        "description": "A stranded scientist pieces together an impossible mission with the kind of momentum that makes chapters evaporate.",
        "rating": 9.3,
        "release_year": 2021,
        "season_label": "Weekend read",
        "status": "Always recommendable",
        "is_hot": True,
        "featured": False,
        "image_url": "https://placehold.co/1200x720/0369a1/f8fafc?text=Project+Hail+Mary",
    },
    {
        "title": "Dune",
        "media_type": "book",
        "genre": "Epic Sci-Fi",
        "tagline": "Politics, prophecy, and sand at impossible scale.",
        "description": "Dense, strange, and still one of the most rewarding entry points into truly gigantic science-fiction worldbuilding.",
        "rating": 9.0,
        "release_year": 1965,
        "season_label": "Classic heavyweight",
        "status": "Evergreen giant",
        "is_hot": True,
        "featured": False,
        "image_url": "https://placehold.co/1200x720/b45309/f8fafc?text=Dune",
    },
    {
        "title": "The Poppy War",
        "media_type": "book",
        "genre": "Grimdark Fantasy",
        "tagline": "Starts sharp, then gets brutally intense.",
        "description": "Military fantasy with escalating moral cost, unforgettable rage, and a lead who refuses to stay easy to categorize.",
        "rating": 8.8,
        "release_year": 2018,
        "season_label": "Dark fantasy lane",
        "status": "Heavy but gripping",
        "is_hot": True,
        "featured": False,
        "image_url": "https://placehold.co/1200x720/7f1d1d/f8fafc?text=The+Poppy+War",
    },
    {
        "title": "Severance",
        "media_type": "webseries",
        "genre": "Sci-Fi Thriller",
        "tagline": "Corporate dread turned into prestige puzzle-box television.",
        "description": "An office mystery with immaculate tension, eerie design, and cliffhangers that are rude in the best possible way.",
        "rating": 9.3,
        "release_year": 2022,
        "season_label": "Think-about-it-afterwards",
        "status": "Peak discussion bait",
        "is_hot": True,
        "featured": True,
        "image_url": "https://placehold.co/1200x720/111827/f8fafc?text=Severance",
    },
    {
        "title": "Arcane",
        "media_type": "webseries",
        "genre": "Animated Fantasy",
        "tagline": "Every frame tries to show off and somehow earns it.",
        "description": "Emotionally sharp, visually outrageous, and one of the easiest recommendations when someone says they want something cinematic.",
        "rating": 9.4,
        "release_year": 2021,
        "season_label": "Visual feast",
        "status": "Still a flex",
        "is_hot": True,
        "featured": False,
        "image_url": "https://placehold.co/1200x720/1f2937/f8fafc?text=Arcane",
    },
    {
        "title": "The Bear",
        "media_type": "webseries",
        "genre": "Drama",
        "tagline": "Stress as art, somehow incredibly watchable.",
        "description": "Kitchen chaos, family grief, and character work that feels painfully alive from minute one.",
        "rating": 9.1,
        "release_year": 2022,
        "season_label": "Intense binge",
        "status": "Heat level: high",
        "is_hot": True,
        "featured": False,
        "image_url": "https://placehold.co/1200x720/7c2d12/f8fafc?text=The+Bear",
    },
    {
        "title": "Wednesday",
        "media_type": "webseries",
        "genre": "Dark Comedy",
        "tagline": "Campy, gothic, and very easy to marathon.",
        "description": "A polished supernatural binge with enough attitude, mystery, and meme energy to stay in rotation.",
        "rating": 8.2,
        "release_year": 2022,
        "season_label": "Style-forward binge",
        "status": "Crowd pleaser",
        "is_hot": True,
        "featured": False,
        "image_url": "https://placehold.co/1200x720/374151/f8fafc?text=Wednesday",
    },
]


DISCUSSION_SEED = [
    {
        "topic": "What title has your full attention this week?",
        "description": "Everyone has one show, book, or game that hijacked their brain this week. Drop the title and the one-line reason it instantly moved to the top of the pile.",
        "community": "r/frontpage-watch",
        "author_name": "Ari",
        "topic_type": "general",
        "comment_count": 93,
        "featured": True,
        "upvotes": 538,
        "downvotes": 21,
        "image_url": "https://placehold.co/1200x720/0f172a/f8fafc?text=Weekly+Pulse",
    },
    {
        "topic": "Dandadan or Blue Lock for pure momentum?",
        "description": "If somebody wants something fast, loud, and impossible to watch just one episode of, which one are you handing them first?",
        "community": "r/anime-lounge",
        "author_name": "Mika",
        "topic_type": "anime",
        "comment_count": 58,
        "featured": False,
        "upvotes": 412,
        "downvotes": 17,
        "image_url": "https://placehold.co/1200x720/312e81/f8fafc?text=Anime+Debate",
    },
    {
        "topic": "Balatro, Hades II, or Persona 3 Reload for a late-night session?",
        "description": "The ideal answer probably depends on whether you want flow-state action, card-based nonsense, or story-heavy vibes. Which one wins for you and why?",
        "community": "r/game-room",
        "author_name": "Neo",
        "topic_type": "game",
        "comment_count": 71,
        "featured": False,
        "upvotes": 460,
        "downvotes": 26,
        "image_url": "https://placehold.co/1200x720/14532d/f8fafc?text=Game+Night",
    },
    {
        "topic": "Books that feel impossible to stop after chapter three",
        "description": "Not necessarily the greatest book ever written. Just the one with chapter pacing so mean that your bedtime gets cancelled.",
        "community": "r/book-nook",
        "author_name": "Rey",
        "topic_type": "book",
        "comment_count": 44,
        "featured": False,
        "upvotes": 301,
        "downvotes": 8,
        "image_url": "https://placehold.co/1200x720/92400e/f8fafc?text=Book+Rush",
    },
    {
        "topic": "Which web series currently has the best cliffhangers?",
        "description": "Not just a good ending. The kind that makes you stare at the next-episode button with zero self-control.",
        "community": "r/binge-club",
        "author_name": "Jun",
        "topic_type": "webseries",
        "comment_count": 67,
        "featured": False,
        "upvotes": 389,
        "downvotes": 13,
        "image_url": "https://placehold.co/1200x720/1f2937/f8fafc?text=Binge+Club",
    },
    {
        "topic": "What gets something dropped fastest for you?",
        "description": "Bad pacing, weak dialogue, repetitive side quests, or just no chemistry at all. Everyone has a deal-breaker, and this is the thread for unapologetic honesty.",
        "community": "r/unitainment",
        "author_name": "Cass",
        "topic_type": "general",
        "comment_count": 39,
        "featured": False,
        "upvotes": 250,
        "downvotes": 19,
        "image_url": "https://placehold.co/1200x720/334155/f8fafc?text=Drop+Zone",
    },
]


def seed_catalog(apps, schema_editor):
    Media = apps.get_model("mainapp", "Media")
    Discussion = apps.get_model("mainapp", "Discussion")

    for media in MEDIA_SEED:
        Media.objects.update_or_create(title=media["title"], defaults=media)

    for discussion in DISCUSSION_SEED:
        Discussion.objects.update_or_create(topic=discussion["topic"], defaults=discussion)


def unseed_catalog(apps, schema_editor):
    Media = apps.get_model("mainapp", "Media")
    Discussion = apps.get_model("mainapp", "Discussion")

    Media.objects.filter(title__in=[media["title"] for media in MEDIA_SEED]).delete()
    Discussion.objects.filter(topic__in=[discussion["topic"] for discussion in DISCUSSION_SEED]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_searchhistory_alter_personallist_user_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_catalog, unseed_catalog),
    ]
